### PR TITLE
Fix for Hue initialization on HA cluster

### LINKED ISSUE #324: Hue does not initialize on HA clusters
Init action cannot be successfully completed on HA configuration (does not matter on which dataproc version).

I found that's because of missing mysql service on additional master nodes - I found it is installed only on m-0. 

I will submit PR with required changes. In PR I will fix also problem with failure on database operation using mysql for additional master nodes. Before script starts doing action on database, mysql restart operation should be performed.

```
+ mysql -u root -proot-password -e '     CREATE DATABASE hue;     CREATE USER '\''hue'\''@'\''localhost'\'' IDENTIFIED BY '\''hue-password'\'';     GRANT ALL PRIVILEGES ON hue.* TO '\''hue'\''@'\''localhost'\'';'
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
+ err 'Unable to create database'
```

It is already fixed in #325 .

### PR DESCRIPTION
**Pull request by adam-stasiak**
I added step for installation mysql service on additional master nodes if needed. I also moved mysql restart operation earlier to avoid problem with database creation on dataproc 1.3 image. 
This PR fixed #324

### CODE REVIEW

**Comment by karth295** [comment]
Rather than running a separate Hue instance on every master node, a simpler fix is just to run it on `-m-0`. That's what I did in `jupyter2`, for example.

**Comment by adam-stasiak** [comment]
@karth295 applied your suggestion -  now I check which node is a "main" master (not additional one) and then compare hostname to that one.

**Comment by adam-stasiak** [comment]
Thx @karth295 for the response. I tested init action on those configs and all succeeded. Could you give me more details? Does init action fail for you?

Port is set based on   ```hdfs getconf -confKey dfs.namenode.http-address```:
```
local new_hdfs_url='webhdfs_url\=http:\/\/'"$(hdfs getconf -confKey dfs.namenode.http-address)" 
```
and documentation says it is ```

The address and the base port where the dfs namenode web ui will listen on.
```. I tried this running on various configurations (image ver.) and returns a value that seems to be ok – for HA 1.1 it is 50070 as you said but for 1.2 and 1.3 HA it is 9870.

The second issue - I will look on this now.

**Comment by karth295** [comment]
The init action succeeded, I just saw those errors when I opened the web ui.

**Comment by adam-stasiak** [comment]
Thanks! I will look on this.

**Comment by medb** [comment]
This PR is obsolete, Hue init action muse have been fixed some time ago.

**Pull request closed without merging**
