### PR TITLE
Apache Toree kernel added.

### PR DESCRIPTION
**Pull request by piffall**

### CODE REVIEW

**Comment by karth295** [comment]
Thanks for your PR -- I'll take a closer look in a couple days.

Does this Toree kernel purely provide additions on top of the existing pyspark kernel? If so, rather than having two different kernels, can we just make one kernel that's pyspark+toree?

Also, if you have a chance, please add a note in the README on what Toree is and link to the Toree docs.

**Comment by jaguirrepeman** [comment]
The URL in the toree kernel (https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0-incubating-rc5/toree-pip/toree-0.2.0.tar.gz) does not seem to be available.

**Comment by andre-sasaki** [comment]
Kernel cant be downloaded, URL is broken (https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0-incubating-rc5/toree-pip/toree-0.2.0.tar.gz)

**Comment by andre-sasaki** [comment]
I've created a PR that fixes it temporally, please reference to #440

**Comment by MaxAVF** [comment]
Same problem here  
```
  HTTP error 404 while getting https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0-incubating-rc5/toree-pip/toree-0.2.0.tar.gz
  Could not install requirement https://dist.apache.org/repos/dist/dev/incubator/toree/0.2.0-incubating-rc5/toree-pip/toree-0.2.0.tar.gz because of error 404 Client

```

**Comment by barendlinders** [comment]
It's a shame this broken PR managed to be merged... You'd hope someone/something would pick up the 404.

**Comment by aniket486** [comment]
Sorry about that. Unfortunately, I did not see a failure during manual testing when launching a cluster using this initialization-action. We plan to work on automating this process with tests so that we can catch such failures sooner.

**Comment by aniket486** [comment]
@barendlinders I tried to investigate why my manual testing failed in this case. This is because jupyter initialization action is quite different from other dataproc initialization action. Jupyter init action relies on clone of the scripts in master repo - regardless of what --initialization-action points to.
https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/jupyter/jupyter.sh#L26

**Pull request merged**
