### PR TITLE
add spark-bigquery to zeppelin

### PR DESCRIPTION
**Pull request by nevillelyh**

### CODE REVIEW

**Comment by nevillelyh** [comment]
I signed it!

**Comment by nevillelyh** [comment]
Hi I work for Spotify and we already signed a company CLA.

**Comment by pmkc** [comment]
Hi Neville,

I'll look into your CLA.

I hadn't realized https://github.com/spotify/spark-bigquery existed. I have been meaning to write something similar, but it seems pretty neat, As for adding it to Zeppelin isn't

```
%dep
load("spotify:spark-bigquery_2.10:0.1.0")
```

sufficient? It seems better to let users customize their Classpaths however they like.

-Patrick

**Comment by nevillelyh** [comment]
@pmkc sounds good. Do check out spark-bigquery and let me know what you think.
Closing this for now.

**Pull request closed without merging**
