### PR TITLE
BUG: (DS-699) Add —allow-root flag to jupyter command runs for config…

### PR DESCRIPTION
**Pull request by nehalecky**
… generation and launching, supporting changes in Jupyter 5.0.0

### CODE REVIEW

**Comment by nehalecky** [comment]
might also resolve #102?

**Comment by dennishuo** [comment]
Ah, indeed, good catch. Thanks! I'll test and merge as soon as possible.

**Comment by dennishuo** [comment]
Tested cleanly:

    gcloud dataproc clusters create dhuo-jupyter-fixed \
        --initialization-actions gs://dataproc-initialization-actions/jupyter/jupyter.sh \
        --metadata "INIT_ACTIONS_REPO=https://github.com/bomboradata/dataproc-initialization-actions.git,INIT_ACTIONS_BRANCH=fix-jupyter-5.0.0-config-and-launch"

Thanks for sending the fix!

**Comment by nehalecky** [comment]
@dennishuo, np! Glad to help out. This morning, when my analysis cluster didn't start, I knew it was likely related to something around the Jupyter 5.0.0 update. Sorry I didn't get it out sooner!

**Comment by devpog** [comment]
Hi there,

Doesn't seem like modules are being properly loaded with pyspark kernel, although the init process boots ok now
screen shot 2017-04-06 at 11 10 25 am

**Comment by nehalecky** [comment]
@devpog, that's correct (not due to Jupyter update) and unfortunate. Like many Py3 code bases, this is due to the removal of tuple unpacking in Python 3.6, which not one of us understands. :/

On the dataproc provisioning side, the issue manifests due to the most version of miniconda3 (e.g. the env var leverages in `bootstrap-conda.sh` defaulting to `MINICONDA_VER`='latest'`, which in turn now defaults to Python 3.6. To circumvent this, you have a few options available within use of this repo:
1)  explicitly target an older miniconda version when provisioning with `bootstrap-conda.sh` via the evn var as `export MINICONDA_VER='4.2.12'`), which currently resolves to Python 3.5.2
2) passing in an additional init action script that creates and uses a custom conda environment, which has python set  (e.g., `python<=3.5.3`)
3) My least favorite option, because it's a step backwards: set miniconda variant to 2 via `export MINICONDA_VARIANT='2'`, which resolves to install most recent version of Python 2 (i.e., `2.7.13`). Note, this won't this won't help if your code base is written in Python 3.

HTH, and if needed, I can probably find some time to submit a PR that has a sample script, using option 1 above (and later a combination of 2). :)

**Comment by devpog** [comment]
@nehalecky thanks! was thinking about 3.5 conda's env )

**Comment by dennishuo** [comment]
I'm going to take a stab at reintroducing the metadata options for MINICONDA_VARIANT and MINICONDA_VERSION (it was broken before due to using "-v" for variable being set instead of "-z" for variable being empty whether or not it was set), and also pin default to 4.2.12 for now.

**Comment by dennishuo** [comment]
FYI - merged https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/106/files

**Comment by nehalecky** [comment]
@dennishuo, great. Until it is fixed upstream in Spark, that's definitely the best solution. Thanks much!

**Pull request merged**
