### PR TITLE
Drill integration tests

### PR DESCRIPTION
**Pull request by adam-stasiak**
These scripts can be used for testing Drill init action on single, standard and ha configurations.

### CODE REVIEW

**Comment by functicons** [comment]
I checked out the PR locally and tried run the test, but it failed:

$ python -m unittest drill.test_drill
EEEEEE
======================================================================
ERROR: test_drill.mode: HA.version: 1_2-deb9 (drill.test_drill.DrillTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/dagang/venv/venv3.5/lib/python3.5/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/usr/local/google/home/dagang/repo/github/GoogleCloudPlatform/dataproc-initialization-actions/drill/test_drill.py", line 55, in test_drill
    "{}-{}".format(self.getClusterName(), target_machine_suffix),
  File "/usr/local/google/home/dagang/repo/github/GoogleCloudPlatform/dataproc-initialization-actions/drill/test_drill.py", line 17, in verify_instance
    self.upload_test_file(name)
TypeError: upload_test_file() missing 1 required positional argument: 'name'

**Comment by adam-stasiak** [comment]
Now it should be fixed. Recently the way how we upload test files has changed.

**Comment by functicons** [comment]
Thanks for the fix, this time it failed with a different error:

$ python -m unittest drill.test_drill
FFFFFF
======================================================================
FAIL: test_drill.mode: HA.version: 1_2-deb9 (drill.test_drill.DrillTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/dagang/venv/venv3.5/lib/python3.5/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/usr/local/google/home/dagang/repo/github/GoogleCloudPlatform/dataproc-initialization-actions/drill/test_drill.py", line 55, in test_drill
    "{}-{}".format(self.getClusterName(), target_machine_suffix),
  File "/usr/local/google/home/dagang/repo/github/GoogleCloudPlatform/dataproc-initialization-actions/drill/test_drill.py", line 17, in verify_instance
    self.upload_test_file(self.TEST_SCRIPT_FILE_NAME,name)
  File "/usr/local/google/home/dagang/repo/github/GoogleCloudPlatform/dataproc-initialization-actions/integration_tests/dataproc_test_case.py", line 90, in upload_test_file
    self.assertEqual(ret_code, 0, "Failed to upload test file. Error: {}".format(stderr))
AssertionError: 1 != 0 : Failed to upload test file. Error: WARNING: Using OS Login user [dagang_google_com] instead of default user [dagang]
Warning: Permanently added 'compute.2916503282617720157' (ECDSA) to the list of known hosts.
validate.sh: No such file or directory
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].

**Comment by functicons** [comment]
I tested it again, it was stuck, no result was shown on the command line. 

$ python -m unittest drill.test_drill
(no output and hang here)

I can find the test cluster test-drill-ha-1-2-deb9-20190108130448 in my project. Could you paste your test result here?

**Comment by adam-stasiak** [comment]
@functicons You're right - in the meantime new releases of Drill were published and link that I was using with ```wget``` command was expired. I changed this link to apache archive site with the newest release ```1.15.0```.
I tried with command and got no error.
```python3 -m unittest drill.test_drill```
When launch with PyCharm it is also ok.

Please remember about putting correct gs:// address with the newest version of drill.sh script.

**Comment by functicons** [comment]
@adam-stasiak I tested again, the same problem, `python3.5 -m unittest drill.test_drill` got stuck. Could you add some debug information to show the progress?

**Comment by adam-stasiak** [comment]
I investigated this thing and found that drill.sh placed in dataproc-initialization-actions bucket is outdated and still uses us apache link instead of archive apache.
```
 # Download and unpack Drill as the pseudo-user.
  sudo wget http://www-us.apache.org/dist/drill/drill-${DRILL_VERSION}/apache-drill-${DRILL_VERSION}.tar.gz 
```
but should be:
```
  wget https://archive.apache.org/dist/drill/drill-${DRILL_VERSION}/apache-drill-${DRILL_VERSION}.tar.gz || \
```

This change came with this PR and init action should be replaced with the newest one. 

Please update   
```
INIT_ACTION = 'gs://dataproc-initialization-actions/drill/drill.sh'
INIT_ACTION_FOR_STANDARD = '\'gs://dataproc-initialization-actions/zookeeper/zookeeper.sh\',\'gs://dataproc-initialization-actions/drill/drill.sh\''
```
with the proper gs:// paths. After merge of this PR and updated init action in dataproc-intialization-actions, tests should pass without any restrictions.

**Comment by functicons** [comment]
@adam-stasiak Could you extract the change to drill.sh into a separate PR? I'll review, approve and upload. Then we will come back to review the test.

**Comment by functicons** [comment]
@adam-stasiak any update? I'm expecting a separate CL just for drill.sh changes.

**Comment by adam-stasiak** [comment]
@functicons Hi, i've just created separated [PR](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/432) for drill.sh. In this PR reverted changes on drill.sh file.

Please take a look on this :) Please remember to use drill.sh file from #432.

**Comment by functicons** [comment]
@adam-stasiak I have merged #432 and pushed drill.sh to the GCS bucket. But I see merge conflict for drill/drill.sh in this PR. It is not completely reverted, drill.sh still appear in the changed files list.

**Comment by functicons** [comment]
Tests passed. Could you resolve the drill.sh conflict, then I will approve.

**Comment by adam-stasiak** [comment]
@functicons Hi, I made requested change.

**Pull request merged**
