### PR TITLE
Install Conda Packages

### PR DESCRIPTION
**Pull request by AviNash15**
1) Copy bootstrap-conda.sh and install-conda-env.sh to your bucket

Then run this script
# Install Miniconda / conda
gsutil -m cp gs://Your Bucket/bootstrap-conda.sh ./
gsutil -m cp gs://Your Bucket/install-conda-env.sh ./
chmod 755 bootstrap-conda.sh install-conda-env.sh
./bootstrap-conda.sh

# Update conda root environment with specific packages in pip and conda
CONDA_PACKAGES='pandas scikit-learn'
PIP_PACKAGES='plotly cufflinks'
CONDA_PACKAGES=$CONDA_PACKAGES PIP_PACKAGES=$PIP_PACKAGES ./install-conda-env.sh

### CODE REVIEW

**Comment by AviNash15** [comment]
I signed it!

**Comment by karth295** [comment]
These instructions are already in the README, right? Why add another file?

**Comment by AviNash15** [comment]
Instructions in README are poorly documented.

**Comment by karth295** [comment]
If I understand correctly, the README uses the (poorly documented) magical copy of this repo present on the VMs (`./dataproc-initialization-actions/conda/bootstrap-conda.sh`). In your PR you want to specify a GCS path.

Do you mind sending us a PR with your proposed changes to the README?

**Pull request closed without merging**
